# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUserStory3():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_createNewAppointment(self):
    self.driver.get("http://3.238.20.218:8080/")
    self.driver.set_window_size(1346, 809)
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(2) span:nth-child(2)").click()
    self.driver.find_element(By.ID, "lastName").click()
    self.driver.find_element(By.ID, "lastName").send_keys("Wells")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) a").click()
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(2) > a").click()
    self.driver.find_element(By.ID, "description").click()
    self.driver.find_element(By.ID, "description").send_keys("Test Apt")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
  def test_negTestNoRequiredfieldsenteredforAppointment(self):
    self.driver.get("http://3.238.20.218:8080/")
    self.driver.set_window_size(1346, 809)
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(2) span:nth-child(2)").click()
    self.driver.find_element(By.ID, "lastName").click()
    self.driver.find_element(By.ID, "lastName").send_keys("Wells")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) a").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > td:nth-child(2) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
