# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUserStory1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_negTestNoRequiredPetOwnerInfoEntered(self):
    self.driver.get("http://3.238.20.218:8080/")
    self.driver.set_window_size(1346, 809)
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(2) > .nav-link").click()
    self.driver.find_element(By.LINK_TEXT, "Add Owner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
  def test_negTestAlphaCharactersinTelephonefield(self):
    self.driver.get("http://3.238.20.218:8080/")
    self.driver.set_window_size(1346, 809)
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(2) span:nth-child(2)").click()
    self.driver.find_element(By.LINK_TEXT, "Add Owner").click()
    self.driver.find_element(By.ID, "firstName").click()
    self.driver.find_element(By.ID, "firstName").send_keys("Mika")
    self.driver.find_element(By.ID, "lastName").send_keys("Wells")
    self.driver.find_element(By.ID, "address").send_keys("12 Test")
    self.driver.find_element(By.ID, "city").send_keys("Test")
    self.driver.find_element(By.ID, "telephone").click()
    self.driver.find_element(By.ID, "telephone").send_keys("Alpha char")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
  def test_createNewPetOwnerContactInfo(self):
    self.driver.get("http://3.238.20.218:8080/")
    self.driver.set_window_size(1346, 809)
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(2) > .nav-link").click()
    self.driver.find_element(By.LINK_TEXT, "Add Owner").click()
    self.driver.find_element(By.ID, "firstName").click()
    self.driver.find_element(By.ID, "firstName").send_keys("Mika")
    self.driver.find_element(By.ID, "lastName").send_keys("Wells")
    self.driver.find_element(By.ID, "address").send_keys("12 Test Lane")
    self.driver.find_element(By.ID, "city").send_keys("Test")
    self.driver.find_element(By.ID, "telephone").send_keys("3148248676")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
